# fly.toml app configuration file generated for my-laravel-app-wild-morning-2437 on 2025-01-03T19:42:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-laravel-app-wild-morning-2437'
primary_region = 'mad'

[build]
  dockerfile = 'Dockerfile.prod'

[env]
  APP_ENV = 'production'
  DB_CONNECTION = 'pgsql'
  DB_DATABASE = 'postgres'
  DB_HOST = 'spring-smoke-8624.internal'
  DB_PASSWORD = 'Jc2sI1Ouz62htbu'
  DB_PORT = '5432'
  DB_USERNAME = 'postgres'

[[services]]
  protocol = 'tcp'
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ['http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
